apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: payments
  labels:
    app: payment-service
data:
  # Server configuration
  PORT: "8080"
  GIN_MODE: "release"
  DEBUG: "false"
  SERVER_READ_TIMEOUT: "15"
  SERVER_WRITE_TIMEOUT: "15"
  SERVER_SHUTDOWN_TIMEOUT: "30"

  # Database configuration
  DB_HOST: "postgres-payment-service"
  DB_PORT: "5432"
  DB_NAME: "payment_service"
  DB_SSLMODE: "disable"

  # Kafka configuration
  KAFKA_BROKERS: "kafka-broker:9092"
  KAFKA_CONSUMER_GROUP: "payment-service"
  KAFKA_CONSUMER_OFFSET: "earliest"

  # Logging
  LOG_LEVEL: "info"

  # Timeouts
  HTTP_CLIENT_TIMEOUT: "30"

  # Service dependencies
  NOTIFICATION_SERVICE_URL: "http://notification-service:8080"
  USER_SERVICE_URL: "http://user-service:8080"

  # Feature flags
  ENABLE_WEBHOOKS: "true"
  ENABLE_METRICS: "true"
  ENABLE_PAYMENT_METHODS_CACHE: "true"
  ENABLE_STRIPE_INTEGRATION: "true"

  # Metrics
  METRICS_UPDATE_INTERVAL: "15"

  # Additional configuration
  PAYMENT_RETRY_MAX_ATTEMPTS: "3"
  PAYMENT_RETRY_INITIAL_DELAY: "5"
  PAYMENT_RETRY_MAX_DELAY: "60"
  PAYMENT_RETRY_BACKOFF_FACTOR: "2"

  # Supported payment methods and currencies
  SUPPORTED_PAYMENT_METHODS: "card,bank_transfer"
  SUPPORTED_CURRENCIES: "USD,EUR,RUB"